name: Build gRPC with vcpkg

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Show vcpkg location
        shell: pwsh
        run: |
          Write-Host "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT"
          & "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe" version

      - name: Build gRPC
        shell: pwsh
        run: |
          & "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe" install grpc:x64-windows

      - name: Upload compiled package
        uses: actions/upload-artifact@v4
        with:
          name: grpc-x64-windows
          path: ${{ env.VCPKG_INSTALLATION_ROOT }}\installed\x64-windows